// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/tours": {
    params: {};
  };
  "/tours/tour/:id": {
    params: {
      "id": string;
    };
  };
  "/account/details": {
    params: {};
  };
  "/account/bookings": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/contact-us": {
    params: {};
  };
  "/privacy-policy": {
    params: {};
  };
  "/terms-of-usage": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/tours": {
    params: {};
  };
  "/admin/tours/add": {
    params: {};
  };
  "/admin/tours/edit/:id": {
    params: {
      "id": string;
    };
  };
  "/admin/registrations": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/logout" | "/login" | "/signup" | "/tours" | "/tours/tour/:id" | "/account/details" | "/account/bookings" | "/about" | "/contact-us" | "/privacy-policy" | "/terms-of-usage" | "/admin" | "/admin/tours" | "/admin/tours/add" | "/admin/tours/edit/:id" | "/admin/registrations" | "/*";
  };
  "./routes/_actions/logout.tsx": {
    id: "routes/_actions/logout";
    page: "/logout";
  };
  "./routes/layout.tsx": {
    id: "routes/layout";
    page: "/" | "/login" | "/signup" | "/tours" | "/tours/tour/:id" | "/account/details" | "/account/bookings" | "/about" | "/contact-us" | "/privacy-policy" | "/terms-of-usage";
  };
  "routes/Home/home.tsx": {
    id: "routes/Home/home";
    page: "/";
  };
  "./routes/Auth/login.tsx": {
    id: "routes/Auth/login";
    page: "/login";
  };
  "./routes/Auth/signup.tsx": {
    id: "routes/Auth/signup";
    page: "/signup";
  };
  "./routes/Tour/tours.tsx": {
    id: "routes/Tour/tours";
    page: "/tours";
  };
  "./routes/Tour/tour-details.tsx": {
    id: "routes/Tour/tour-details";
    page: "/tours/tour/:id";
  };
  "./routes/Account/account-layout.tsx": {
    id: "routes/Account/account-layout";
    page: "/account/details" | "/account/bookings";
  };
  "./routes/Account/account-details.tsx": {
    id: "routes/Account/account-details";
    page: "/account/details";
  };
  "./routes/Account/my-bookings.tsx": {
    id: "routes/Account/my-bookings";
    page: "/account/bookings";
  };
  "./routes/About/about.tsx": {
    id: "routes/About/about";
    page: "/about";
  };
  "./routes/Contact/contact-us.tsx": {
    id: "routes/Contact/contact-us";
    page: "/contact-us";
  };
  "./routes/Miscellaneous/PrivacyPolicy.tsx": {
    id: "routes/Miscellaneous/PrivacyPolicy";
    page: "/privacy-policy";
  };
  "./routes/Miscellaneous/TermsOfUsage.tsx": {
    id: "routes/Miscellaneous/TermsOfUsage";
    page: "/terms-of-usage";
  };
  "./routes/admin/layout.tsx": {
    id: "routes/admin/layout";
    page: "/admin" | "/admin/tours" | "/admin/tours/add" | "/admin/tours/edit/:id" | "/admin/registrations";
  };
  "./routes/admin/dashboard.tsx": {
    id: "routes/admin/dashboard";
    page: "/admin";
  };
  "./routes/admin/Tours/tours.tsx": {
    id: "routes/admin/Tours/tours";
    page: "/admin/tours";
  };
  "./routes/admin/Tours/add-tour.tsx": {
    id: "routes/admin/Tours/add-tour";
    page: "/admin/tours/add";
  };
  "./routes/admin/Tours/update-tour.tsx": {
    id: "routes/admin/Tours/update-tour";
    page: "/admin/tours/edit/:id";
  };
  "./routes/admin/Booking/bookings.tsx": {
    id: "routes/admin/Booking/bookings";
    page: "/admin/registrations";
  };
  "./routes/Error/404.tsx": {
    id: "routes/Error/404";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_actions/logout": typeof import("./app/./routes/_actions/logout.tsx");
  "routes/layout": typeof import("./app/./routes/layout.tsx");
  "routes/Home/home": typeof import("./app/routes/Home/home.tsx");
  "routes/Auth/login": typeof import("./app/./routes/Auth/login.tsx");
  "routes/Auth/signup": typeof import("./app/./routes/Auth/signup.tsx");
  "routes/Tour/tours": typeof import("./app/./routes/Tour/tours.tsx");
  "routes/Tour/tour-details": typeof import("./app/./routes/Tour/tour-details.tsx");
  "routes/Account/account-layout": typeof import("./app/./routes/Account/account-layout.tsx");
  "routes/Account/account-details": typeof import("./app/./routes/Account/account-details.tsx");
  "routes/Account/my-bookings": typeof import("./app/./routes/Account/my-bookings.tsx");
  "routes/About/about": typeof import("./app/./routes/About/about.tsx");
  "routes/Contact/contact-us": typeof import("./app/./routes/Contact/contact-us.tsx");
  "routes/Miscellaneous/PrivacyPolicy": typeof import("./app/./routes/Miscellaneous/PrivacyPolicy.tsx");
  "routes/Miscellaneous/TermsOfUsage": typeof import("./app/./routes/Miscellaneous/TermsOfUsage.tsx");
  "routes/admin/layout": typeof import("./app/./routes/admin/layout.tsx");
  "routes/admin/dashboard": typeof import("./app/./routes/admin/dashboard.tsx");
  "routes/admin/Tours/tours": typeof import("./app/./routes/admin/Tours/tours.tsx");
  "routes/admin/Tours/add-tour": typeof import("./app/./routes/admin/Tours/add-tour.tsx");
  "routes/admin/Tours/update-tour": typeof import("./app/./routes/admin/Tours/update-tour.tsx");
  "routes/admin/Booking/bookings": typeof import("./app/./routes/admin/Booking/bookings.tsx");
  "routes/Error/404": typeof import("./app/./routes/Error/404.tsx");
};